package win.forexam.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import win.forexam.model.AnswerSheet;
import win.forexam.model.AnswerSheetExample;

public interface AnswerSheetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet
     *
     * @mbggenerated Wed Mar 23 17:50:13 CST 2016
     */
    int countByExample(AnswerSheetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet
     *
     * @mbggenerated Wed Mar 23 17:50:13 CST 2016
     */
    int deleteByExample(AnswerSheetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet
     *
     * @mbggenerated Wed Mar 23 17:50:13 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet
     *
     * @mbggenerated Wed Mar 23 17:50:13 CST 2016
     */
    int insert(AnswerSheet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet
     *
     * @mbggenerated Wed Mar 23 17:50:13 CST 2016
     */
    int insertSelective(AnswerSheet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet
     *
     * @mbggenerated Wed Mar 23 17:50:13 CST 2016
     */
    List<AnswerSheet> selectByExample(AnswerSheetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet
     *
     * @mbggenerated Wed Mar 23 17:50:13 CST 2016
     */
    AnswerSheet selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet
     *
     * @mbggenerated Wed Mar 23 17:50:13 CST 2016
     */
    int updateByExampleSelective(@Param("record") AnswerSheet record, @Param("example") AnswerSheetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet
     *
     * @mbggenerated Wed Mar 23 17:50:13 CST 2016
     */
    int updateByExample(@Param("record") AnswerSheet record, @Param("example") AnswerSheetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet
     *
     * @mbggenerated Wed Mar 23 17:50:13 CST 2016
     */
    int updateByPrimaryKeySelective(AnswerSheet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet
     *
     * @mbggenerated Wed Mar 23 17:50:13 CST 2016
     */
    int updateByPrimaryKey(AnswerSheet record);
}