package win.forexam.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import win.forexam.model.AnswerSheetQuestion;
import win.forexam.model.AnswerSheetQuestionExample;

public interface AnswerSheetQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet_question
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    int countByExample(AnswerSheetQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet_question
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    int deleteByExample(AnswerSheetQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet_question
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet_question
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    int insert(AnswerSheetQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet_question
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    int insertSelective(AnswerSheetQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet_question
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    List<AnswerSheetQuestion> selectByExample(AnswerSheetQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet_question
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    AnswerSheetQuestion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet_question
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    int updateByExampleSelective(@Param("record") AnswerSheetQuestion record, @Param("example") AnswerSheetQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet_question
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    int updateByExample(@Param("record") AnswerSheetQuestion record, @Param("example") AnswerSheetQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet_question
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    int updateByPrimaryKeySelective(AnswerSheetQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet_question
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    int updateByPrimaryKey(AnswerSheetQuestion record);
}