package win.forexam.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AnswerSheetExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ex_answer_sheet
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ex_answer_sheet
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ex_answer_sheet
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public AnswerSheetExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_answer_sheet
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ex_answer_sheet
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDifficultyIsNull() {
            addCriterion("difficulty is null");
            return (Criteria) this;
        }

        public Criteria andDifficultyIsNotNull() {
            addCriterion("difficulty is not null");
            return (Criteria) this;
        }

        public Criteria andDifficultyEqualTo(Integer value) {
            addCriterion("difficulty =", value, "difficulty");
            return (Criteria) this;
        }

        public Criteria andDifficultyNotEqualTo(Integer value) {
            addCriterion("difficulty <>", value, "difficulty");
            return (Criteria) this;
        }

        public Criteria andDifficultyGreaterThan(Integer value) {
            addCriterion("difficulty >", value, "difficulty");
            return (Criteria) this;
        }

        public Criteria andDifficultyGreaterThanOrEqualTo(Integer value) {
            addCriterion("difficulty >=", value, "difficulty");
            return (Criteria) this;
        }

        public Criteria andDifficultyLessThan(Integer value) {
            addCriterion("difficulty <", value, "difficulty");
            return (Criteria) this;
        }

        public Criteria andDifficultyLessThanOrEqualTo(Integer value) {
            addCriterion("difficulty <=", value, "difficulty");
            return (Criteria) this;
        }

        public Criteria andDifficultyIn(List<Integer> values) {
            addCriterion("difficulty in", values, "difficulty");
            return (Criteria) this;
        }

        public Criteria andDifficultyNotIn(List<Integer> values) {
            addCriterion("difficulty not in", values, "difficulty");
            return (Criteria) this;
        }

        public Criteria andDifficultyBetween(Integer value1, Integer value2) {
            addCriterion("difficulty between", value1, value2, "difficulty");
            return (Criteria) this;
        }

        public Criteria andDifficultyNotBetween(Integer value1, Integer value2) {
            addCriterion("difficulty not between", value1, value2, "difficulty");
            return (Criteria) this;
        }

        public Criteria andScoreIsNull() {
            addCriterion("score is null");
            return (Criteria) this;
        }

        public Criteria andScoreIsNotNull() {
            addCriterion("score is not null");
            return (Criteria) this;
        }

        public Criteria andScoreEqualTo(Integer value) {
            addCriterion("score =", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotEqualTo(Integer value) {
            addCriterion("score <>", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThan(Integer value) {
            addCriterion("score >", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("score >=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThan(Integer value) {
            addCriterion("score <", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThanOrEqualTo(Integer value) {
            addCriterion("score <=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreIn(List<Integer> values) {
            addCriterion("score in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotIn(List<Integer> values) {
            addCriterion("score not in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreBetween(Integer value1, Integer value2) {
            addCriterion("score between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("score not between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andStudentNumberIsNull() {
            addCriterion("student_number is null");
            return (Criteria) this;
        }

        public Criteria andStudentNumberIsNotNull() {
            addCriterion("student_number is not null");
            return (Criteria) this;
        }

        public Criteria andStudentNumberEqualTo(Integer value) {
            addCriterion("student_number =", value, "studentNumber");
            return (Criteria) this;
        }

        public Criteria andStudentNumberNotEqualTo(Integer value) {
            addCriterion("student_number <>", value, "studentNumber");
            return (Criteria) this;
        }

        public Criteria andStudentNumberGreaterThan(Integer value) {
            addCriterion("student_number >", value, "studentNumber");
            return (Criteria) this;
        }

        public Criteria andStudentNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("student_number >=", value, "studentNumber");
            return (Criteria) this;
        }

        public Criteria andStudentNumberLessThan(Integer value) {
            addCriterion("student_number <", value, "studentNumber");
            return (Criteria) this;
        }

        public Criteria andStudentNumberLessThanOrEqualTo(Integer value) {
            addCriterion("student_number <=", value, "studentNumber");
            return (Criteria) this;
        }

        public Criteria andStudentNumberIn(List<Integer> values) {
            addCriterion("student_number in", values, "studentNumber");
            return (Criteria) this;
        }

        public Criteria andStudentNumberNotIn(List<Integer> values) {
            addCriterion("student_number not in", values, "studentNumber");
            return (Criteria) this;
        }

        public Criteria andStudentNumberBetween(Integer value1, Integer value2) {
            addCriterion("student_number between", value1, value2, "studentNumber");
            return (Criteria) this;
        }

        public Criteria andStudentNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("student_number not between", value1, value2, "studentNumber");
            return (Criteria) this;
        }

        public Criteria andQuestionNumberIsNull() {
            addCriterion("question_number is null");
            return (Criteria) this;
        }

        public Criteria andQuestionNumberIsNotNull() {
            addCriterion("question_number is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionNumberEqualTo(Integer value) {
            addCriterion("question_number =", value, "questionNumber");
            return (Criteria) this;
        }

        public Criteria andQuestionNumberNotEqualTo(Integer value) {
            addCriterion("question_number <>", value, "questionNumber");
            return (Criteria) this;
        }

        public Criteria andQuestionNumberGreaterThan(Integer value) {
            addCriterion("question_number >", value, "questionNumber");
            return (Criteria) this;
        }

        public Criteria andQuestionNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("question_number >=", value, "questionNumber");
            return (Criteria) this;
        }

        public Criteria andQuestionNumberLessThan(Integer value) {
            addCriterion("question_number <", value, "questionNumber");
            return (Criteria) this;
        }

        public Criteria andQuestionNumberLessThanOrEqualTo(Integer value) {
            addCriterion("question_number <=", value, "questionNumber");
            return (Criteria) this;
        }

        public Criteria andQuestionNumberIn(List<Integer> values) {
            addCriterion("question_number in", values, "questionNumber");
            return (Criteria) this;
        }

        public Criteria andQuestionNumberNotIn(List<Integer> values) {
            addCriterion("question_number not in", values, "questionNumber");
            return (Criteria) this;
        }

        public Criteria andQuestionNumberBetween(Integer value1, Integer value2) {
            addCriterion("question_number between", value1, value2, "questionNumber");
            return (Criteria) this;
        }

        public Criteria andQuestionNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("question_number not between", value1, value2, "questionNumber");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andChannelIsNull() {
            addCriterion("channel is null");
            return (Criteria) this;
        }

        public Criteria andChannelIsNotNull() {
            addCriterion("channel is not null");
            return (Criteria) this;
        }

        public Criteria andChannelEqualTo(Integer value) {
            addCriterion("channel =", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotEqualTo(Integer value) {
            addCriterion("channel <>", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThan(Integer value) {
            addCriterion("channel >", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThanOrEqualTo(Integer value) {
            addCriterion("channel >=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThan(Integer value) {
            addCriterion("channel <", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThanOrEqualTo(Integer value) {
            addCriterion("channel <=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelIn(List<Integer> values) {
            addCriterion("channel in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotIn(List<Integer> values) {
            addCriterion("channel not in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelBetween(Integer value1, Integer value2) {
            addCriterion("channel between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotBetween(Integer value1, Integer value2) {
            addCriterion("channel not between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andPropertiesIsNull() {
            addCriterion("properties is null");
            return (Criteria) this;
        }

        public Criteria andPropertiesIsNotNull() {
            addCriterion("properties is not null");
            return (Criteria) this;
        }

        public Criteria andPropertiesEqualTo(String value) {
            addCriterion("properties =", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesNotEqualTo(String value) {
            addCriterion("properties <>", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesGreaterThan(String value) {
            addCriterion("properties >", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesGreaterThanOrEqualTo(String value) {
            addCriterion("properties >=", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesLessThan(String value) {
            addCriterion("properties <", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesLessThanOrEqualTo(String value) {
            addCriterion("properties <=", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesLike(String value) {
            addCriterion("properties like", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesNotLike(String value) {
            addCriterion("properties not like", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesIn(List<String> values) {
            addCriterion("properties in", values, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesNotIn(List<String> values) {
            addCriterion("properties not in", values, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesBetween(String value1, String value2) {
            addCriterion("properties between", value1, value2, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesNotBetween(String value1, String value2) {
            addCriterion("properties not between", value1, value2, "properties");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("memo is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("memo is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("memo =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("memo <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("memo >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("memo >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("memo <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("memo <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("memo like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("memo not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("memo in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("memo not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("memo between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("memo not between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdIsNull() {
            addCriterion("question_id is null");
            return (Criteria) this;
        }

        public Criteria andQuestionIdIsNotNull() {
            addCriterion("question_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionIdEqualTo(Long value) {
            addCriterion("question_id =", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotEqualTo(Long value) {
            addCriterion("question_id <>", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdGreaterThan(Long value) {
            addCriterion("question_id >", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdGreaterThanOrEqualTo(Long value) {
            addCriterion("question_id >=", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdLessThan(Long value) {
            addCriterion("question_id <", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdLessThanOrEqualTo(Long value) {
            addCriterion("question_id <=", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdIn(List<Long> values) {
            addCriterion("question_id in", values, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotIn(List<Long> values) {
            addCriterion("question_id not in", values, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdBetween(Long value1, Long value2) {
            addCriterion("question_id between", value1, value2, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotBetween(Long value1, Long value2) {
            addCriterion("question_id not between", value1, value2, "questionId");
            return (Criteria) this;
        }

        public Criteria andTag1IsNull() {
            addCriterion("tag1 is null");
            return (Criteria) this;
        }

        public Criteria andTag1IsNotNull() {
            addCriterion("tag1 is not null");
            return (Criteria) this;
        }

        public Criteria andTag1EqualTo(Integer value) {
            addCriterion("tag1 =", value, "tag1");
            return (Criteria) this;
        }

        public Criteria andTag1NotEqualTo(Integer value) {
            addCriterion("tag1 <>", value, "tag1");
            return (Criteria) this;
        }

        public Criteria andTag1GreaterThan(Integer value) {
            addCriterion("tag1 >", value, "tag1");
            return (Criteria) this;
        }

        public Criteria andTag1GreaterThanOrEqualTo(Integer value) {
            addCriterion("tag1 >=", value, "tag1");
            return (Criteria) this;
        }

        public Criteria andTag1LessThan(Integer value) {
            addCriterion("tag1 <", value, "tag1");
            return (Criteria) this;
        }

        public Criteria andTag1LessThanOrEqualTo(Integer value) {
            addCriterion("tag1 <=", value, "tag1");
            return (Criteria) this;
        }

        public Criteria andTag1In(List<Integer> values) {
            addCriterion("tag1 in", values, "tag1");
            return (Criteria) this;
        }

        public Criteria andTag1NotIn(List<Integer> values) {
            addCriterion("tag1 not in", values, "tag1");
            return (Criteria) this;
        }

        public Criteria andTag1Between(Integer value1, Integer value2) {
            addCriterion("tag1 between", value1, value2, "tag1");
            return (Criteria) this;
        }

        public Criteria andTag1NotBetween(Integer value1, Integer value2) {
            addCriterion("tag1 not between", value1, value2, "tag1");
            return (Criteria) this;
        }

        public Criteria andTag2IsNull() {
            addCriterion("tag2 is null");
            return (Criteria) this;
        }

        public Criteria andTag2IsNotNull() {
            addCriterion("tag2 is not null");
            return (Criteria) this;
        }

        public Criteria andTag2EqualTo(Integer value) {
            addCriterion("tag2 =", value, "tag2");
            return (Criteria) this;
        }

        public Criteria andTag2NotEqualTo(Integer value) {
            addCriterion("tag2 <>", value, "tag2");
            return (Criteria) this;
        }

        public Criteria andTag2GreaterThan(Integer value) {
            addCriterion("tag2 >", value, "tag2");
            return (Criteria) this;
        }

        public Criteria andTag2GreaterThanOrEqualTo(Integer value) {
            addCriterion("tag2 >=", value, "tag2");
            return (Criteria) this;
        }

        public Criteria andTag2LessThan(Integer value) {
            addCriterion("tag2 <", value, "tag2");
            return (Criteria) this;
        }

        public Criteria andTag2LessThanOrEqualTo(Integer value) {
            addCriterion("tag2 <=", value, "tag2");
            return (Criteria) this;
        }

        public Criteria andTag2In(List<Integer> values) {
            addCriterion("tag2 in", values, "tag2");
            return (Criteria) this;
        }

        public Criteria andTag2NotIn(List<Integer> values) {
            addCriterion("tag2 not in", values, "tag2");
            return (Criteria) this;
        }

        public Criteria andTag2Between(Integer value1, Integer value2) {
            addCriterion("tag2 between", value1, value2, "tag2");
            return (Criteria) this;
        }

        public Criteria andTag2NotBetween(Integer value1, Integer value2) {
            addCriterion("tag2 not between", value1, value2, "tag2");
            return (Criteria) this;
        }

        public Criteria andTag3IsNull() {
            addCriterion("tag3 is null");
            return (Criteria) this;
        }

        public Criteria andTag3IsNotNull() {
            addCriterion("tag3 is not null");
            return (Criteria) this;
        }

        public Criteria andTag3EqualTo(Integer value) {
            addCriterion("tag3 =", value, "tag3");
            return (Criteria) this;
        }

        public Criteria andTag3NotEqualTo(Integer value) {
            addCriterion("tag3 <>", value, "tag3");
            return (Criteria) this;
        }

        public Criteria andTag3GreaterThan(Integer value) {
            addCriterion("tag3 >", value, "tag3");
            return (Criteria) this;
        }

        public Criteria andTag3GreaterThanOrEqualTo(Integer value) {
            addCriterion("tag3 >=", value, "tag3");
            return (Criteria) this;
        }

        public Criteria andTag3LessThan(Integer value) {
            addCriterion("tag3 <", value, "tag3");
            return (Criteria) this;
        }

        public Criteria andTag3LessThanOrEqualTo(Integer value) {
            addCriterion("tag3 <=", value, "tag3");
            return (Criteria) this;
        }

        public Criteria andTag3In(List<Integer> values) {
            addCriterion("tag3 in", values, "tag3");
            return (Criteria) this;
        }

        public Criteria andTag3NotIn(List<Integer> values) {
            addCriterion("tag3 not in", values, "tag3");
            return (Criteria) this;
        }

        public Criteria andTag3Between(Integer value1, Integer value2) {
            addCriterion("tag3 between", value1, value2, "tag3");
            return (Criteria) this;
        }

        public Criteria andTag3NotBetween(Integer value1, Integer value2) {
            addCriterion("tag3 not between", value1, value2, "tag3");
            return (Criteria) this;
        }

        public Criteria andTag4IsNull() {
            addCriterion("tag4 is null");
            return (Criteria) this;
        }

        public Criteria andTag4IsNotNull() {
            addCriterion("tag4 is not null");
            return (Criteria) this;
        }

        public Criteria andTag4EqualTo(Integer value) {
            addCriterion("tag4 =", value, "tag4");
            return (Criteria) this;
        }

        public Criteria andTag4NotEqualTo(Integer value) {
            addCriterion("tag4 <>", value, "tag4");
            return (Criteria) this;
        }

        public Criteria andTag4GreaterThan(Integer value) {
            addCriterion("tag4 >", value, "tag4");
            return (Criteria) this;
        }

        public Criteria andTag4GreaterThanOrEqualTo(Integer value) {
            addCriterion("tag4 >=", value, "tag4");
            return (Criteria) this;
        }

        public Criteria andTag4LessThan(Integer value) {
            addCriterion("tag4 <", value, "tag4");
            return (Criteria) this;
        }

        public Criteria andTag4LessThanOrEqualTo(Integer value) {
            addCriterion("tag4 <=", value, "tag4");
            return (Criteria) this;
        }

        public Criteria andTag4In(List<Integer> values) {
            addCriterion("tag4 in", values, "tag4");
            return (Criteria) this;
        }

        public Criteria andTag4NotIn(List<Integer> values) {
            addCriterion("tag4 not in", values, "tag4");
            return (Criteria) this;
        }

        public Criteria andTag4Between(Integer value1, Integer value2) {
            addCriterion("tag4 between", value1, value2, "tag4");
            return (Criteria) this;
        }

        public Criteria andTag4NotBetween(Integer value1, Integer value2) {
            addCriterion("tag4 not between", value1, value2, "tag4");
            return (Criteria) this;
        }

        public Criteria andTag5IsNull() {
            addCriterion("tag5 is null");
            return (Criteria) this;
        }

        public Criteria andTag5IsNotNull() {
            addCriterion("tag5 is not null");
            return (Criteria) this;
        }

        public Criteria andTag5EqualTo(Integer value) {
            addCriterion("tag5 =", value, "tag5");
            return (Criteria) this;
        }

        public Criteria andTag5NotEqualTo(Integer value) {
            addCriterion("tag5 <>", value, "tag5");
            return (Criteria) this;
        }

        public Criteria andTag5GreaterThan(Integer value) {
            addCriterion("tag5 >", value, "tag5");
            return (Criteria) this;
        }

        public Criteria andTag5GreaterThanOrEqualTo(Integer value) {
            addCriterion("tag5 >=", value, "tag5");
            return (Criteria) this;
        }

        public Criteria andTag5LessThan(Integer value) {
            addCriterion("tag5 <", value, "tag5");
            return (Criteria) this;
        }

        public Criteria andTag5LessThanOrEqualTo(Integer value) {
            addCriterion("tag5 <=", value, "tag5");
            return (Criteria) this;
        }

        public Criteria andTag5In(List<Integer> values) {
            addCriterion("tag5 in", values, "tag5");
            return (Criteria) this;
        }

        public Criteria andTag5NotIn(List<Integer> values) {
            addCriterion("tag5 not in", values, "tag5");
            return (Criteria) this;
        }

        public Criteria andTag5Between(Integer value1, Integer value2) {
            addCriterion("tag5 between", value1, value2, "tag5");
            return (Criteria) this;
        }

        public Criteria andTag5NotBetween(Integer value1, Integer value2) {
            addCriterion("tag5 not between", value1, value2, "tag5");
            return (Criteria) this;
        }

        public Criteria andTag6IsNull() {
            addCriterion("tag6 is null");
            return (Criteria) this;
        }

        public Criteria andTag6IsNotNull() {
            addCriterion("tag6 is not null");
            return (Criteria) this;
        }

        public Criteria andTag6EqualTo(Integer value) {
            addCriterion("tag6 =", value, "tag6");
            return (Criteria) this;
        }

        public Criteria andTag6NotEqualTo(Integer value) {
            addCriterion("tag6 <>", value, "tag6");
            return (Criteria) this;
        }

        public Criteria andTag6GreaterThan(Integer value) {
            addCriterion("tag6 >", value, "tag6");
            return (Criteria) this;
        }

        public Criteria andTag6GreaterThanOrEqualTo(Integer value) {
            addCriterion("tag6 >=", value, "tag6");
            return (Criteria) this;
        }

        public Criteria andTag6LessThan(Integer value) {
            addCriterion("tag6 <", value, "tag6");
            return (Criteria) this;
        }

        public Criteria andTag6LessThanOrEqualTo(Integer value) {
            addCriterion("tag6 <=", value, "tag6");
            return (Criteria) this;
        }

        public Criteria andTag6In(List<Integer> values) {
            addCriterion("tag6 in", values, "tag6");
            return (Criteria) this;
        }

        public Criteria andTag6NotIn(List<Integer> values) {
            addCriterion("tag6 not in", values, "tag6");
            return (Criteria) this;
        }

        public Criteria andTag6Between(Integer value1, Integer value2) {
            addCriterion("tag6 between", value1, value2, "tag6");
            return (Criteria) this;
        }

        public Criteria andTag6NotBetween(Integer value1, Integer value2) {
            addCriterion("tag6 not between", value1, value2, "tag6");
            return (Criteria) this;
        }

        public Criteria andTag7IsNull() {
            addCriterion("tag7 is null");
            return (Criteria) this;
        }

        public Criteria andTag7IsNotNull() {
            addCriterion("tag7 is not null");
            return (Criteria) this;
        }

        public Criteria andTag7EqualTo(Integer value) {
            addCriterion("tag7 =", value, "tag7");
            return (Criteria) this;
        }

        public Criteria andTag7NotEqualTo(Integer value) {
            addCriterion("tag7 <>", value, "tag7");
            return (Criteria) this;
        }

        public Criteria andTag7GreaterThan(Integer value) {
            addCriterion("tag7 >", value, "tag7");
            return (Criteria) this;
        }

        public Criteria andTag7GreaterThanOrEqualTo(Integer value) {
            addCriterion("tag7 >=", value, "tag7");
            return (Criteria) this;
        }

        public Criteria andTag7LessThan(Integer value) {
            addCriterion("tag7 <", value, "tag7");
            return (Criteria) this;
        }

        public Criteria andTag7LessThanOrEqualTo(Integer value) {
            addCriterion("tag7 <=", value, "tag7");
            return (Criteria) this;
        }

        public Criteria andTag7In(List<Integer> values) {
            addCriterion("tag7 in", values, "tag7");
            return (Criteria) this;
        }

        public Criteria andTag7NotIn(List<Integer> values) {
            addCriterion("tag7 not in", values, "tag7");
            return (Criteria) this;
        }

        public Criteria andTag7Between(Integer value1, Integer value2) {
            addCriterion("tag7 between", value1, value2, "tag7");
            return (Criteria) this;
        }

        public Criteria andTag7NotBetween(Integer value1, Integer value2) {
            addCriterion("tag7 not between", value1, value2, "tag7");
            return (Criteria) this;
        }

        public Criteria andTag8IsNull() {
            addCriterion("tag8 is null");
            return (Criteria) this;
        }

        public Criteria andTag8IsNotNull() {
            addCriterion("tag8 is not null");
            return (Criteria) this;
        }

        public Criteria andTag8EqualTo(Integer value) {
            addCriterion("tag8 =", value, "tag8");
            return (Criteria) this;
        }

        public Criteria andTag8NotEqualTo(Integer value) {
            addCriterion("tag8 <>", value, "tag8");
            return (Criteria) this;
        }

        public Criteria andTag8GreaterThan(Integer value) {
            addCriterion("tag8 >", value, "tag8");
            return (Criteria) this;
        }

        public Criteria andTag8GreaterThanOrEqualTo(Integer value) {
            addCriterion("tag8 >=", value, "tag8");
            return (Criteria) this;
        }

        public Criteria andTag8LessThan(Integer value) {
            addCriterion("tag8 <", value, "tag8");
            return (Criteria) this;
        }

        public Criteria andTag8LessThanOrEqualTo(Integer value) {
            addCriterion("tag8 <=", value, "tag8");
            return (Criteria) this;
        }

        public Criteria andTag8In(List<Integer> values) {
            addCriterion("tag8 in", values, "tag8");
            return (Criteria) this;
        }

        public Criteria andTag8NotIn(List<Integer> values) {
            addCriterion("tag8 not in", values, "tag8");
            return (Criteria) this;
        }

        public Criteria andTag8Between(Integer value1, Integer value2) {
            addCriterion("tag8 between", value1, value2, "tag8");
            return (Criteria) this;
        }

        public Criteria andTag8NotBetween(Integer value1, Integer value2) {
            addCriterion("tag8 not between", value1, value2, "tag8");
            return (Criteria) this;
        }

        public Criteria andTag9IsNull() {
            addCriterion("tag9 is null");
            return (Criteria) this;
        }

        public Criteria andTag9IsNotNull() {
            addCriterion("tag9 is not null");
            return (Criteria) this;
        }

        public Criteria andTag9EqualTo(Integer value) {
            addCriterion("tag9 =", value, "tag9");
            return (Criteria) this;
        }

        public Criteria andTag9NotEqualTo(Integer value) {
            addCriterion("tag9 <>", value, "tag9");
            return (Criteria) this;
        }

        public Criteria andTag9GreaterThan(Integer value) {
            addCriterion("tag9 >", value, "tag9");
            return (Criteria) this;
        }

        public Criteria andTag9GreaterThanOrEqualTo(Integer value) {
            addCriterion("tag9 >=", value, "tag9");
            return (Criteria) this;
        }

        public Criteria andTag9LessThan(Integer value) {
            addCriterion("tag9 <", value, "tag9");
            return (Criteria) this;
        }

        public Criteria andTag9LessThanOrEqualTo(Integer value) {
            addCriterion("tag9 <=", value, "tag9");
            return (Criteria) this;
        }

        public Criteria andTag9In(List<Integer> values) {
            addCriterion("tag9 in", values, "tag9");
            return (Criteria) this;
        }

        public Criteria andTag9NotIn(List<Integer> values) {
            addCriterion("tag9 not in", values, "tag9");
            return (Criteria) this;
        }

        public Criteria andTag9Between(Integer value1, Integer value2) {
            addCriterion("tag9 between", value1, value2, "tag9");
            return (Criteria) this;
        }

        public Criteria andTag9NotBetween(Integer value1, Integer value2) {
            addCriterion("tag9 not between", value1, value2, "tag9");
            return (Criteria) this;
        }

        public Criteria andTag10IsNull() {
            addCriterion("tag10 is null");
            return (Criteria) this;
        }

        public Criteria andTag10IsNotNull() {
            addCriterion("tag10 is not null");
            return (Criteria) this;
        }

        public Criteria andTag10EqualTo(Integer value) {
            addCriterion("tag10 =", value, "tag10");
            return (Criteria) this;
        }

        public Criteria andTag10NotEqualTo(Integer value) {
            addCriterion("tag10 <>", value, "tag10");
            return (Criteria) this;
        }

        public Criteria andTag10GreaterThan(Integer value) {
            addCriterion("tag10 >", value, "tag10");
            return (Criteria) this;
        }

        public Criteria andTag10GreaterThanOrEqualTo(Integer value) {
            addCriterion("tag10 >=", value, "tag10");
            return (Criteria) this;
        }

        public Criteria andTag10LessThan(Integer value) {
            addCriterion("tag10 <", value, "tag10");
            return (Criteria) this;
        }

        public Criteria andTag10LessThanOrEqualTo(Integer value) {
            addCriterion("tag10 <=", value, "tag10");
            return (Criteria) this;
        }

        public Criteria andTag10In(List<Integer> values) {
            addCriterion("tag10 in", values, "tag10");
            return (Criteria) this;
        }

        public Criteria andTag10NotIn(List<Integer> values) {
            addCriterion("tag10 not in", values, "tag10");
            return (Criteria) this;
        }

        public Criteria andTag10Between(Integer value1, Integer value2) {
            addCriterion("tag10 between", value1, value2, "tag10");
            return (Criteria) this;
        }

        public Criteria andTag10NotBetween(Integer value1, Integer value2) {
            addCriterion("tag10 not between", value1, value2, "tag10");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ex_answer_sheet
     *
     * @mbggenerated do_not_delete_during_merge Wed Mar 23 20:43:31 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ex_answer_sheet
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}