package win.forexam.model;

import java.util.Date;

public class AnswerSheet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_answer_sheet.ID
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_answer_sheet.name
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_answer_sheet.difficulty
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    private Integer difficulty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_answer_sheet.score
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_answer_sheet.student_number
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    private Integer studentNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_answer_sheet.question_number
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    private Integer questionNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_answer_sheet.create_time
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_answer_sheet.modify_time
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_answer_sheet.status
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_answer_sheet.channel
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    private Integer channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_answer_sheet.properties
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    private String properties;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_answer_sheet.memo
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_answer_sheet.user_id
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_answer_sheet.question_id
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    private Long questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_answer_sheet.tag1
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    private Integer tag1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_answer_sheet.tag2
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    private Integer tag2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_answer_sheet.tag3
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    private Integer tag3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_answer_sheet.tag4
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    private Integer tag4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_answer_sheet.tag5
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    private Integer tag5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_answer_sheet.tag6
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    private Integer tag6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_answer_sheet.tag7
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    private Integer tag7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_answer_sheet.tag8
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    private Integer tag8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_answer_sheet.tag9
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    private Integer tag9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_answer_sheet.tag10
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    private Integer tag10;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_answer_sheet.ID
     *
     * @return the value of ex_answer_sheet.ID
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_answer_sheet.ID
     *
     * @param id the value for ex_answer_sheet.ID
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_answer_sheet.name
     *
     * @return the value of ex_answer_sheet.name
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_answer_sheet.name
     *
     * @param name the value for ex_answer_sheet.name
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_answer_sheet.difficulty
     *
     * @return the value of ex_answer_sheet.difficulty
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public Integer getDifficulty() {
        return difficulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_answer_sheet.difficulty
     *
     * @param difficulty the value for ex_answer_sheet.difficulty
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public void setDifficulty(Integer difficulty) {
        this.difficulty = difficulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_answer_sheet.score
     *
     * @return the value of ex_answer_sheet.score
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_answer_sheet.score
     *
     * @param score the value for ex_answer_sheet.score
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_answer_sheet.student_number
     *
     * @return the value of ex_answer_sheet.student_number
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public Integer getStudentNumber() {
        return studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_answer_sheet.student_number
     *
     * @param studentNumber the value for ex_answer_sheet.student_number
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public void setStudentNumber(Integer studentNumber) {
        this.studentNumber = studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_answer_sheet.question_number
     *
     * @return the value of ex_answer_sheet.question_number
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public Integer getQuestionNumber() {
        return questionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_answer_sheet.question_number
     *
     * @param questionNumber the value for ex_answer_sheet.question_number
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public void setQuestionNumber(Integer questionNumber) {
        this.questionNumber = questionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_answer_sheet.create_time
     *
     * @return the value of ex_answer_sheet.create_time
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_answer_sheet.create_time
     *
     * @param createTime the value for ex_answer_sheet.create_time
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_answer_sheet.modify_time
     *
     * @return the value of ex_answer_sheet.modify_time
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_answer_sheet.modify_time
     *
     * @param modifyTime the value for ex_answer_sheet.modify_time
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_answer_sheet.status
     *
     * @return the value of ex_answer_sheet.status
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_answer_sheet.status
     *
     * @param status the value for ex_answer_sheet.status
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_answer_sheet.channel
     *
     * @return the value of ex_answer_sheet.channel
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public Integer getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_answer_sheet.channel
     *
     * @param channel the value for ex_answer_sheet.channel
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public void setChannel(Integer channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_answer_sheet.properties
     *
     * @return the value of ex_answer_sheet.properties
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public String getProperties() {
        return properties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_answer_sheet.properties
     *
     * @param properties the value for ex_answer_sheet.properties
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public void setProperties(String properties) {
        this.properties = properties == null ? null : properties.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_answer_sheet.memo
     *
     * @return the value of ex_answer_sheet.memo
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_answer_sheet.memo
     *
     * @param memo the value for ex_answer_sheet.memo
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_answer_sheet.user_id
     *
     * @return the value of ex_answer_sheet.user_id
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_answer_sheet.user_id
     *
     * @param userId the value for ex_answer_sheet.user_id
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_answer_sheet.question_id
     *
     * @return the value of ex_answer_sheet.question_id
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_answer_sheet.question_id
     *
     * @param questionId the value for ex_answer_sheet.question_id
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_answer_sheet.tag1
     *
     * @return the value of ex_answer_sheet.tag1
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public Integer getTag1() {
        return tag1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_answer_sheet.tag1
     *
     * @param tag1 the value for ex_answer_sheet.tag1
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public void setTag1(Integer tag1) {
        this.tag1 = tag1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_answer_sheet.tag2
     *
     * @return the value of ex_answer_sheet.tag2
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public Integer getTag2() {
        return tag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_answer_sheet.tag2
     *
     * @param tag2 the value for ex_answer_sheet.tag2
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public void setTag2(Integer tag2) {
        this.tag2 = tag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_answer_sheet.tag3
     *
     * @return the value of ex_answer_sheet.tag3
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public Integer getTag3() {
        return tag3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_answer_sheet.tag3
     *
     * @param tag3 the value for ex_answer_sheet.tag3
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public void setTag3(Integer tag3) {
        this.tag3 = tag3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_answer_sheet.tag4
     *
     * @return the value of ex_answer_sheet.tag4
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public Integer getTag4() {
        return tag4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_answer_sheet.tag4
     *
     * @param tag4 the value for ex_answer_sheet.tag4
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public void setTag4(Integer tag4) {
        this.tag4 = tag4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_answer_sheet.tag5
     *
     * @return the value of ex_answer_sheet.tag5
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public Integer getTag5() {
        return tag5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_answer_sheet.tag5
     *
     * @param tag5 the value for ex_answer_sheet.tag5
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public void setTag5(Integer tag5) {
        this.tag5 = tag5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_answer_sheet.tag6
     *
     * @return the value of ex_answer_sheet.tag6
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public Integer getTag6() {
        return tag6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_answer_sheet.tag6
     *
     * @param tag6 the value for ex_answer_sheet.tag6
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public void setTag6(Integer tag6) {
        this.tag6 = tag6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_answer_sheet.tag7
     *
     * @return the value of ex_answer_sheet.tag7
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public Integer getTag7() {
        return tag7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_answer_sheet.tag7
     *
     * @param tag7 the value for ex_answer_sheet.tag7
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public void setTag7(Integer tag7) {
        this.tag7 = tag7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_answer_sheet.tag8
     *
     * @return the value of ex_answer_sheet.tag8
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public Integer getTag8() {
        return tag8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_answer_sheet.tag8
     *
     * @param tag8 the value for ex_answer_sheet.tag8
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public void setTag8(Integer tag8) {
        this.tag8 = tag8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_answer_sheet.tag9
     *
     * @return the value of ex_answer_sheet.tag9
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public Integer getTag9() {
        return tag9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_answer_sheet.tag9
     *
     * @param tag9 the value for ex_answer_sheet.tag9
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public void setTag9(Integer tag9) {
        this.tag9 = tag9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_answer_sheet.tag10
     *
     * @return the value of ex_answer_sheet.tag10
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public Integer getTag10() {
        return tag10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_answer_sheet.tag10
     *
     * @param tag10 the value for ex_answer_sheet.tag10
     *
     * @mbggenerated Wed Mar 23 20:43:31 CST 2016
     */
    public void setTag10(Integer tag10) {
        this.tag10 = tag10;
    }
}